# Generated by Django 2.2.4 on 2019-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190901_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='resident', max_length=10),
        ),
    ]
