# Generated by Django 2.2.4 on 2019-09-04 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190904_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='township',
            name='registration_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
