# Generated by Django 2.2.4 on 2019-09-07 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190904_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='rate',
            new_name='billing_rate',
        ),
        migrations.RenameField(
            model_name='wing',
            old_name='apt_per_floor',
            new_name='apts_per_floor',
        ),
        migrations.AddField(
            model_name='amenity',
            name='time_period',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='amenity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Amenity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='billing_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='billing_to',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wing',
            name='naming_convention',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
