# Generated by Django 2.2.4 on 2019-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190912_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='free_for_members',
            field=models.BooleanField(default=False),
        ),
    ]
