# Generated by Django 2.2.4 on 2019-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190913_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
