# Generated by Django 2.2.4 on 2019-09-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_user_profile_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
