# Generated by Django 2.2.4 on 2019-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amt_time_period',
            field=models.IntegerField(default=1),
        ),
    ]
