# Generated by Django 2.2.4 on 2019-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190922_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='verification_link',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
