# Generated by Django 2.2.4 on 2019-09-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_township_verification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='verification_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
