# Generated by Django 2.2.4 on 2019-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20190924_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='paytm_checksumhash',
            field=models.CharField(blank=True, default=None, max_length=108, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paytm_order_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paytm_transaction_status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paytm_cust_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
