# Generated by Django 2.2.4 on 2019-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_townshippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='paytm_cust_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='townshippayment',
            name='paytm_transaction_status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
