# Generated by Django 2.2.4 on 2019-09-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_user_paytm_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paytm_cust_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
