# Generated by Django 2.2.4 on 2019-10-02 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20191001_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='township',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Township'),
        ),
        migrations.AddField(
            model_name='notice',
            name='wings',
            field=models.ManyToManyField(to='backend.Wing'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
