# Generated by Django 2.2.4 on 2019-10-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20191002_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='posted_by',
        ),
    ]
