# Generated by Django 2.2.4 on 2019-10-19 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20191002_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='in_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='out_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
