# Generated by Django 2.2.4 on 2019-10-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20191019_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='township',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Township'),
        ),
    ]
