# Generated by Django 2.2.4 on 2019-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20191023_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='audit_period_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='township',
            name='audit_period_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
