# Generated by Django 2.2.4 on 2019-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_payment_township'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevendor',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicevendor',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicevendor',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicevendor',
            name='work',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
