# Generated by Django 2.2.4 on 2019-10-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20191026_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='township',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Township'),
        ),
    ]
