# Generated by Django 2.2.4 on 2020-02-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_vehicleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='township',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Township'),
        ),
    ]
